apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yzbp0u4t2-go
  janus-idp.io/tekton: yzbp0u4t2-go
  backstage.io/kubernetes-id: yzbp0u4t2-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yzbp0u4t2-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
