apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yzbp0u4t2-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: nexus-docker-nexus.apps.rosa.rhtap-services.xmdt.p3.openshiftapps.com/rhtap/rhtap-qe-go:1c6625ebbfb8c3194763fffbde56070b2588780d@sha256:c22fd5fd2513cf6df6284a95b936ca7ed8c6a83c1e79e35121ac3b906a9f0076
          name: container-image
